---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: client
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/OussamaMaroufi/k8s-vite-react-example.git
  ref:
    branch: main
