---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  releaseName: kyverno
  interval: 1h0m0s
  chart:
    spec:
      chart: kyverno
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      version: "3.6.0"
  values:
    installCRDs: true  # <-- ensures CRDs are created first
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno/values.yaml

