---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno-policies
spec:
  releaseName: kyverno-policies
  chart:
    spec:
      chart: kyverno-policies
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      version: "2.1.0"
  interval: 1h0m0s
  dependsOn:
    - name: kyverno
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/kyverno/kyverno/blob/main/charts/kyverno-policies/values.yaml
  values:
    podSecurityStandard: baseline
    podSecuritySeverity: medium
    validationFailureAction: audit   # enforce  audit not recommended for prod

